spring:
  application:
    name: review-genius-agent
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
  #  ai:
  #    ollama:
  #      base-url: http://localhost:11434
  #      chat:
  #        model: deepseek-r1:8b

github:
  token: ${LOG_INTELLIGENCE_GITHUB_ACCESS_TOKEN_FOR_PR_REVIEW}
  remoteFetchDisabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: WARN
    org.apache.catalina: WARN

agent:
  maxSteps: 5
  retry:
    maxRetries: 2
  llm:
    client:
      disabled: true
  prompt:
    version: REVIEW_V3

