spring:
  application:
    name: review-genius-agent
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
  #  ai:
  #    ollama:
  #      base-url: http://localhost:11434
  #      chat:
  #        model: deepseek-r1:8b

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.web: WARN
    org.apache.catalina: WARN

github:
  token: ${LOG_INTELLIGENCE_GITHUB_ACCESS_TOKEN_FOR_PR_REVIEW}
  remoteFetchDisabled: false

agent:
  retry:
    maxRetries: 2
  analysis:
    chunk-size: 2000
    chunk-analysis-timeout-seconds: 160
  llm:
    client:
      analyze-code:
        disabled: false
      semantic-reflection:
        disabled: false

